import type { CSSProperties } from "react";

interface PhotoProps {
  /** Path to the JPG under /public, starting with "/" (e.g. "/photos/x.jpg"). */
  src: string;
  alt: string;
  /** Intrinsic dimensions - required to reserve space and prevent layout shift. */
  width: number;
  height: number;
  /** Applied to the underlying <img>. */
  className?: string;
  sizes?: string;
  loading?: "lazy" | "eager";
  fetchPriority?: "high" | "low" | "auto";
  decoding?: "async" | "auto" | "sync";
  style?: CSSProperties;
}

const basePath = process.env.NEXT_PUBLIC_BASE_PATH ?? "";

/**
 * Static-export image. Because `output: "export"` disables Next's optimizer,
 * modern formats are pre-generated by `scripts/optimize-images.mjs` as .avif
 * and .webp siblings of each .jpg. This renders a <picture> that serves those
 * to browsers that support them and falls back to the JPG otherwise, while
 * always carrying explicit dimensions + lazy/async decoding.
 *
 * The <picture> uses display:contents so the <img> sizes against the parent
 * (works for both fixed-height and aspect-ratio containers with object-cover).
 */
export default function Photo({
  src,
  alt,
  width,
  height,
  className,
  sizes,
  loading = "lazy",
  fetchPriority,
  decoding = "async",
  style,
}: PhotoProps) {
  const jpg = `${basePath}${src}`;
  const webp = `${basePath}${src.replace(/\.jpe?g$/i, ".webp")}`;
  const avif = `${basePath}${src.replace(/\.jpe?g$/i, ".avif")}`;

  return (
    <picture className="contents">
      <source type="image/avif" srcSet={avif} sizes={sizes} />
      <source type="image/webp" srcSet={webp} sizes={sizes} />
      <img
        src={jpg}
        alt={alt}
        width={width}
        height={height}
        loading={loading}
        decoding={decoding}
        fetchPriority={fetchPriority}
        className={className}
        style={style}
      />
    </picture>
  );
}
